using FlowsXunit.FlowXunitExtensions;
using System.Threading.Tasks;

namespace Requests
{
    [Scenario(@"
* send first request
* send second request
* send third request
* send fourth request
")]
    public partial class RequestFlowAutoGeneratedScenario : FlowSteps<RequestFlowAutoGeneratedScenario.State>, IFlowFailNotRunnedSteps
    {
        public RequestFlowAutoGeneratedScenario(State state) : base(state)
        {

        }

        public partial Task S1_send_first_request()
        {
            return Task.CompletedTask;
        }

        public partial Task S2_send_second_request() { return Task.CompletedTask; }

        public partial Task S3_send_third_request() { return Task.CompletedTask; }

        public partial Task S4_send_fourth_request() { return Task.CompletedTask; }

        public class State { }
    }
}
