name: push-nuget

on:
  push:
    tags:
      - 'v*'

jobs:
  push:
    runs-on: windows-latest
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
    - uses: actions/checkout@v2
    - id: get_version
      uses: battila7/get-version-action@v2
    - run: |
        echo "NuGetVersionV2: ${{ steps.get_version.outputs.version-without-v }}"
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration Release
    - name: Pack with dotnet
      run: dotnet pack Xunit.Scenario.CodeGenerator/Xunit.Scenario.CodeGenerator.csproj --output nuget-packages --configuration Release -p:PackageVersion=${{ steps.get_version.outputs.version-without-v  }}
    - name: Push with dotnet
      run: dotnet nuget push nuget-packages/Xunit.Scenario.CodeGenerator/Xunit.Scenario.CodeGenerator.csproj --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
